# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155945dd78010e54e45f7fb6d28c02dd59c581451dcc7678c888542730bdcac04e5ffbcc0e41578f4bc6783c55333b82f295d73844b3ec583bcb832508ec2709

test:
  secret_key_base: 107b525031685b9a69490e4ee63166f62e5b8d0c137c2038a87e84cadc3804078be1b0a9fce1a7712363532adaee6cabbfa4e949d2dae09af5621ecea7d572a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
